### PR TITLE
Add link to /form

### PR DESCRIPTION
**Pull request by mzampetakis**
Page will redirect to https://bit.ly/3pOHYRl

### CODE REVIEW

**Comment by daknob** [comment]
This is `/form.html` though.. :)

**Comment by mzampetakis** [comment]
This will probably work as https://devstaff.gr/sponsors currently works too (somehow).

**Comment by daknob** [comment]
Interesting!

I would propose a minimum viable HTML, no need for much, and there's also no need to wait 3 seconds:

```
<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8">
      <meta http-equiv="refresh" content="0; URL=https://bit.ly/3pOHYRl" />
   </head>
   <body>
     <p>If you are not redirected, click <a href="https://bit.ly/3pOHYRl">here</a> to go to the Feedback form.</p>
   </body>
</html>
```

**Comment by daknob** [comment]
Also, could we make it e.g. `/feedback` as `/form` could be the Topic Proposal Form or the Raffle Participation Form, ... ?

**Comment by mzampetakis** [comment]
It 's a single form for feedback and Topic Proposal . We currently (on-site meetups) do not use an online form for the Raffle Participation.

**Comment by daknob** [comment]
Well, it's always better to not reserve such a broad term. But up to you.

**Comment by mzampetakis** [comment]
So, removed the 3" delay and renamed page to feedback.html.

**Review by daknob — APPROVED** [review]

**Pull request merged**
